$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: sample-training-pipeline
jobs:

  feature_engineering_job:
    type: command
    description: Generate Training Dataset
    compute: azureml:DS11
    environment:
      conda_file: feature_engineering/conda.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
    code:
      local_path: feature_engineering
    command: >-
      python feature_engineering.py
        --raw_dataset ${{inputs.raw}}/raw.csv
        --training_dataset ${{outputs.training}}/training.csv
    inputs:
      raw:
        folder: azureml://datastores/datalake/paths/raw
        mode: ro_mount
    outputs:
      training:

  training_job:
    type: command
    description: Train Model
    compute: azureml:DS11
    environment:
      conda_file: training/conda.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
    code:
      local_path: training
    command: >-
      python training.py
        --training_dataset ${{inputs.training}}/training.csv
        --model_path ${{outputs.model}}/${{inputs.model_name}}
    inputs:
      training: ${{jobs.feature_engineering_job.outputs.training}}
      model_name: model.pkl
    outputs:
      model:

  evaluation_and_registration_job:
    type: command
    description: Evaluate and Register Model
    compute: azureml:DS11
    environment:
      conda_file: evaluation_and_registration/conda.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
    code:
      local_path: evaluation_and_registration
    command: >-
      python evaluation_and_registration.py
        --model_path ${{inputs.model}}/${{inputs.model_name}}
        --model_name ${{inputs.model_name}}
    inputs:
      model: ${{jobs.training_job.outputs.model}}
      model_name: model.pkl